### ISSUE TITLE
Cannot read properties of undefined (reading 'webhookSubscriptions')

### ISSUE THREAD

**Issue by nickfthedev** [kinngh/shopify-nextjs-prisma-app#15]
Hello,

this is what i get, when I try to run the app. This error comes after I press install on my shop. 

```
---> Error at /auth/tokens TypeError: Cannot read properties of undefined (reading 'webhookSubscriptions')
    at C:\Users\Nick\Code\Shopify\shopify-next-prisma-app\node_modules\@shopify\shopify-api\lib\webhooks\register.js:72:32
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Nick\Code\Shopify\shopify-next-prisma-app\node_modules\tslib\tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
```

This is what my .env looks like:
```
SHOPIFY_API_KEY=xxx
SHOPIFY_API_SECRET=xxx

SHOPIFY_API_SCOPES=read_products,write_products

SHOPIFY_APP_URL= xxx
SHOPIFY_API_VERSION="2023-01" # When deploying to Vercel, don't wrap in ""
## For SQLite
DATABASE_URL=file:./dev.db

ENCRYPTION_STRING= xxx


```
I removed all sensitive data from .env and replaced them with xxx.

**Comment by nickfthedev** [comment]
Removed the comment from the SHOPIFY_API_VERSION Line and removed all whitespaces. 
It's working now!

**Comment by nickfthedev** [comment]
My .env

```
SHOPIFY_API_KEY=xx
SHOPIFY_API_SECRET=xx

# A list of access scopes can be found [here] https://shopify.dev/api/usage/access-scopes
SHOPIFY_API_SCOPES=read_products,write_products

 # Ensure it starts with https://
SHOPIFY_APP_URL=https://9c7c-2a04-4540-7411-8000-b8c0-b168-361b-3b1f.eu.ngrok.io

# When deploying to Vercel, don't wrap in ""
SHOPIFY_API_VERSION=2023-01

## DatabaseURL  For Postgres
#DATABASE_URL="postgresql://username:password@127.0.0.1:5432/shopify-app?schema=public"
## For SQLite
DATABASE_URL=file:./dev.db

ENCRYPTION_STRING=xxx
```
