### ISSUE TITLE
InvalidShopError

### ISSUE THREAD

**Issue by nickfthedev** [kinngh/shopify-nextjs-prisma-app#19]
I use Vercel and i get this error unfortunately: 

```
---> Error at /auth InvalidShopError: Received invalid shop argument
    at /var/task/node_modules/@shopify/shopify-api/lib/utils/shop-validator.js:15:19
    at /var/task/node_modules/@shopify/shopify-api/lib/auth/oauth/oauth.js:25:69
    at Generator.next (<anonymous>)
    at /var/task/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/task/node_modules/tslib/tslib.js:163:16)
    at Object.begin (/var/task/node_modules/@shopify/shopify-api/lib/auth/oauth/oauth.js:20:28)
    at handler (/var/task/.next/server/pages/api/auth.js:57:105)
    at /var/task/node_modules/next/dist/server/api-utils/node.js:392:16
    at /var/task/node_modules/next/dist/server/lib/trace/tracer.js:108:36

```

Tested multiple store but i can't get it to work .. 
Do you maybe know what I am doing wrong?

**Comment by nickfthedev** [comment]
I deleted my entire database and reinstalled the app. It's working now.
